### ISSUE TITLE
`NoMethodError` raised since rails 7.1.0.beta1

### ISSUE THREAD

**Issue by r7kamura** [winebarrel/active_record_mysql_xverify#24]
I switched an app that was working fine with rails 7.0.8 + active_record_mysql_xverify 0.3.0 to rails 7.1.0.beta1 and now I get a `NoMethodError` from here:

https://github.com/winebarrel/active_record_mysql_xverify/blob/36050c1d69ffbe97607ee7b164030619ec69ba7c/lib/active_record_mysql_xverify/utils.rb#L13

Upon investigation, it appears to be caused by the following change that changed the name of the instance variable `@connection` to `@raw_connection`:

- https://github.com/rails/rails/pull/44530

I think this results in `@connection` returning `nil`, and then `nil.query_options` is called.

Before that in the first place, it seems that there is also an error in the following part:

https://github.com/winebarrel/active_record_mysql_xverify/blob/36050c1d69ffbe97607ee7b164030619ec69ba7c/lib/active_record_mysql_xverify/verifier.rb#L9

So, to support both rails versions, we might need code like this?

```ruby
verifier.call(@raw_connection || @connection)
````

**Comment by winebarrel** [comment]
Thanks for the report 😃 
I fixed it in [v0.4.0](https://rubygems.org/gems/active_record_mysql_xverify/versions/0.4.0), please try it.

**Comment by r7kamura** [comment]
@winebarrel Thanks!
I tried the latest version on a medium sized Rails app that we're upgrading from Rails 7.0.8 to 7.1.0 and found it to work fine 👍
